### ISSUE TITLE
Incorrect results in doublet-source panel method example case.

### ISSUE THREAD

**Issue by dingzhw** [GodotMisogi/AeroMDAO#33]
When I ran the case codes, I got that:
`
julia> begin
           airfoil = naca4((2,4,1,2));
           foil    = Foil(airfoil);
           V, α   = 1.0, 3.0;
           uniform = Uniform2D(V, α);
           cl, cls, cms, cps, panels =
               solve_case(foil,
                    uniform;
                    num_panels = 80);
       end;cl
-0.06478979281472284
`

as the result of NACA2412 is around 0.608250
`# result from XFoil when alpha = 3.0 deg and re = 1e5 and mach = 0.0 is 0.608250 ? where is the error?`

**Comment by GodotMisogi** [comment]
Thanks for finding this! The issue was that the NACA 4-digit airfoil generation generates a blunt trailing edge by default. The currently implemented doublet-source panel method does not predict blunt trailing edge airfoils accurately at all, so the default option has been switched to sharp trailing edges.

The latest push 188034ce43c3278c81fa259b0ba6460cb520a720]should fix this issue. The results will not exactly match XFOIL's as the methods are different, but should be somewhat close.

**Comment by dingzhw** [comment]
> Thanks for finding this! The issue was that the NACA 4-digit airfoil generation generates a blunt trailing edge by default. The currently implemented doublet-source panel method does not predict blunt trailing edge airfoils accurately at all, so the default option has been switched to sharp trailing edges.
> 
> The latest push [188034c](https://github.com/GodotMisogi/AeroMDAO/commit/188034ce43c3278c81fa259b0ba6460cb520a720) should fix this issue, so please update AeroMDAO accordingly. The results will not exactly match XFOIL's as the methods are different, but should be somewhat close.

Thank you very much for replying to the question so quickly, the problem is indeed solved, excellent codes, I am reading it carefully and have learned a lot 😀
